Repository xicri/genshin-langdata, pull requests merged in 2022-06, with the labels that each got.

#9 Use secret for Cloudflare Pages deployment hook
  .github/workflows/deploy-dic.yml
Labels: bug

#10 Fix tests to accept Chinese translation contributions
  scripts/release.js
  tests/json5.test.js
Labels: dx

#11 Silently exit MinHon staging deployment when credentials are not available
  scripts/release.js
Labels: bug

#13 Change property name from zh to zhCN
  dataset/dictionary/artifacts.json5
  dataset/dictionary/characters.json5
  dataset/dictionary/enemies.json5
  tests/json5.test.js
Labels: dx

#14 Set up ESLint
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: dx

#15 Add Chinese vocabularies translation
  dataset/dictionary/characters.json5
  dataset/dictionary/domains.json5
Labels: feature

#17 Rewrite README
  README.md
Labels: documentation
